---
language: ruby
bundler_args: --without development
script: "bundle install && bundle exec rake test SPEC_OPTS='--format documentation'"
cache: bundler
sudo: false
branches:
  only:
    - production
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 6.0"
notifications:
  email:
    - lee@leebriggs.co.uk
